server:
  port: 8038
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.45.0.21:3306/was?useUnicode=true&characterEncoding=UTF8
    userName: root
    password: 123456
  application:
    name: fq-modules-was-web
  thymeleaf:
      prefix: classpath:/templates/
      suffix: .html
      mode: LEGACYHTML5
      encoding: UTF-8
      servlet:
        content-type: text/html
      cache: false

eureka:
  client:
    healthcheck:
      enabled: true                           # 开启健康检查（依赖spring-boot-starter-actuator）
    registry-fetch-interval-seconds: 5 # 默认为30秒
    serviceUrl:
        defaultZone: http://10.45.0.54:8761/eureka/

feign:
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

#统一配置feign,动态读取
fq:
  modules:
     was-api:
      serviceId: fq-modules-was-api

